/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ClienteController;
import Controller.EquipoController;
import Controller.ServicioController;
import Controller.SoporteController;
import Model.Equipo;
import Model.Servicio;
import Model.Soporte;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodrigo
 */
public class ClienteEstadoSolicitud extends javax.swing.JFrame {
    private EquipoController cEquipo = new EquipoController();
    private ClienteController cCliente = new ClienteController();
    private ServicioController cServicio = new ServicioController();
    private DefaultTableModel dtmEst = new DefaultTableModel();
    private SoporteController osop = new SoporteController();
    private ClienteEntrada CE = new ClienteEntrada();
    private int IDCliente;
    public ClienteEstadoSolicitud() {
        initComponents();
        llenarTablaEstado();
        setLocationRelativeTo(null);
    }
    public void IDCLIENTE(int ID){
        IDCliente = ID;
        llenarLista();
    }
    
    public void ClienteSaludo(String nombre, String apellido){
        this.LabelCP.setText("Bienvenido "+ nombre + " " + apellido);
    }
    
    public void llenarTablaEstado(){
        dtmEst.addColumn("CODIGO");
        dtmEst.addColumn("MONTO");
        dtmEst.addColumn("DESCRIPCION");
        dtmEst.addColumn("EQUIPO");
        dtmEst.addColumn("SERVICIO");
        dtmEst.addColumn("ESTADO");
        dtmEst.addColumn("SOLUCION");
        this.tEstado.setModel(dtmEst);
    }
    
    public void llenarLista() {
    List<Soporte> lst = osop.getLstSoporteController();
    dtmEst.setRowCount(0);
    for (int i = 0; i < lst.size(); i++) {
        if (lst.get(i).getIDCliente() == IDCliente) {
            Object[] vec = new Object[7];
            Equipo objE = cEquipo.busquedaEquibyID(String.valueOf(lst.get(i).getIDEquipo()));
            Servicio objS = cServicio.busquedaClibyID(String.valueOf(lst.get(i).getIDServicio()));
            vec[0] = lst.get(i).getIDSoporte();
            vec[1] = lst.get(i).getMonto();
            vec[2] = lst.get(i).getDescripcion();
            vec[3] = objE.getDesEquipo();
            vec[4] = objS.getDesServicio();
            vec[5] = lst.get(i).getEstado();
            vec[6] = lst.get(i).getSolucion();
            dtmEst.addRow(vec);
            System.out.println("CODSOP " + lst.get(i).getIDSoporte());
        }
    }
    this.tEstado.setModel(dtmEst);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtras = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tEstado = new javax.swing.JTable();
        LabelCP = new javax.swing.JLabel();
        Label1 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAtras.setBackground(new java.awt.Color(95, 108, 221));
        btnAtras.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(255, 255, 255));
        btnAtras.setText("Cerrar Sesión");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        tEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tEstado);

        LabelCP.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N

        Label1.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        Label1.setText("Mostrando todas las solicitudes hechas por el Cliente...");

        btnNuevo.setBackground(new java.awt.Color(95, 108, 221));
        btnNuevo.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nueva solicitud");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelCP, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 405, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelCP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtras)
                    .addComponent(btnNuevo))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        ClienteEntrada CE = new ClienteEntrada();
        CE.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        ClienteProductos CP = new ClienteProductos();
        CP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteEstadoSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteEstadoSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteEstadoSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteEstadoSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteEstadoSolicitud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel LabelCP;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tEstado;
    // End of variables declaration//GEN-END:variables
}
